In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,99]], np.int64)

In [3]:
myarr

array([[ 3,  4, 99]], dtype=int64)

In [4]:
myarr[0,1]

4

In [5]:
myarr.shape

(1, 3)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
rng = np.arange(15)

In [8]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
lspace = np.linspace(1,5,12)

In [10]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [11]:
emp = np.empty((4,6))

In [12]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        7.56590980e-307, 7.56599807e-307, 1.15706014e-306],
       [1.11260755e-306, 1.42419938e-306, 7.56603881e-307,
        8.45603441e-307, 1.42417221e-306, 1.60219306e-306],
       [6.23059726e-307, 1.06811422e-306, 1.42417221e-306,
        1.37961641e-306, 6.23040033e-307, 6.23053954e-307],
       [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
        1.86921143e-306, 6.23061763e-307, 3.14082521e-317]])

In [13]:
emp_like = np.empty_like(lspace)

In [14]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [15]:
arr = np.arange(99)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [17]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [18]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [19]:
ide = np.identity(45)

In [20]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [21]:
ide.shape

(45, 45)

In [22]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [23]:
ar = np.array(x)

In [24]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
ar.sum(axis=0)

array([12, 15, 18])

In [26]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [27]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [29]:
ar.ndim

2

In [30]:
ar.size

9

In [31]:
ar.nbytes

36

In [32]:
one = np.array([10,2,30,4,5])

In [33]:
one.argmax()

2

In [34]:
one.argmin()

1

In [35]:
one.argsort()

array([1, 3, 4, 0, 2], dtype=int64)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
ar.argmin()

0

In [38]:
ar.argmax()

8

In [39]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [40]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [41]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
ar2 = np.array([[1, 1, 3],
       [4, 5, 6],
       [7, 3, 5]])

In [45]:
ar + ar2

array([[ 2,  3,  6],
       [ 8, 10, 12],
       [14, 11, 14]])

In [46]:
ar * ar2

array([[ 1,  2,  9],
       [16, 25, 36],
       [49, 24, 45]])

In [47]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [48]:
ar.sum()

45

In [49]:
ar.max()

9

In [50]:
ar.min()

1

In [51]:
np.where(ar>3)

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [52]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.where(ar>7)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [55]:
np.count_nonzero(ar)

9

In [56]:
import sys

In [57]:
py_ar = [1,551,147,893]

In [58]:
np_ar = np.array(py_ar)

In [59]:
sys.getsizeof(1) * len(py_ar)

112

In [62]:
np_ar.itemsize * np_ar.size

16

In [63]:
np_ar.tolist()

[1, 551, 147, 893]